{
 "title": "Netology HW 10.3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", mode=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{instance=\"nodeexporter:9100\"}[$__rate_interval]))",
     "legendFormat": "load1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{instance=\"nodeexporter:9100\"}[$__rate_interval]))",
     "legendFormat": "load5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{instance=\"nodeexporter:9100\"}[$__rate_interval]))",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Used FileSystem",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_avail_bytes{fstype!='tmpfs', instance=\"nodeexporter:9100\"} / node_filesystem_size_bytes * 100",
     "legendFormat": "Used FS"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}"
    }
   ]
  }
 ]
}